apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce-platform.configmapName" . }}
  namespace: {{ include "ecommerce-platform.namespace" . }}
  labels:
    {{- include "ecommerce-platform.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrapServers | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otel.endpoint | quote }}
  REDIS_HOST: {{ .Values.global.redis.host | quote }}
  REDIS_PORT: {{ .Values.global.redis.port | quote }}
