package com.ecommerce.orderservice.command;

import com.ecommerce.orderservice.model.OrderItem;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import org.axonframework.modelling.command.TargetAggregateIdentifier;

import java.util.List;

/**
 * Issued by the REST layer to create a new order aggregate.
 * The {@code orderId} is generated by the caller (UUID) so the
 * aggregate identifier is known before the command is sent.
 */
public record CreateOrderCommand(

        @TargetAggregateIdentifier
        @NotBlank
        String orderId,

        @NotBlank
        String customerId,

        @NotEmpty
        @Valid
        List<OrderItem> items,

        @NotBlank
        String shippingAddress
) {}
